### PR TITLE
updated header image, css and background styling

### PR DESCRIPTION
**Pull request by Kay0s**
image

Updated :
header - includes centered logo
card header - added to YouTube player div
background-color - black

The text is currently white, do we want the text to be yellow to match the logo and branding?

### CODE REVIEW

**Comment by Kay0s** [comment]
Here's a mock-up of having gold (warning) text:

image

**Comment by nobleburgundy** [comment]
@Kay0s - should we wait to approve this until the votes are in on which one to go with?

**Comment by Kay0s** [comment]
@James, yes let's have a vote.  So far 2 votes for original logo with gold text.

**Review by klyngdal — APPROVED** [review]
looks great - final tally put side by side and gold text

**Pull request merged**
